name: integration

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - main

env:
  ENV: testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup uv and Python
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Lint Project
      run: uv run ruff check

    - name: Check Formatting
      run: uv run ruff format --check
    
    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  analyze:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup uv and Python
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: AutoBuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: /language:python